name: Deploy to EC2
on: [push]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy to EC2 using SSH key and git clone
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the deployment directory
        
            cd /var/www/edificeweb
            
            # Remove old repository content
            sudo rm -rf ./*
            
            # Clone the latest repository version
            git clone https://github.com/latestbob/edificedevops.git .
            
            # Set correct permissions
            sudo chown -R www-data:www-data /var/www/edificeweb/edificedevops
            sudo chmod -R 755 /var/www/edificeweb/edificedevops
            
            # Restart Nginx
            sudo systemctl restart nginx
